### ISSUE TITLE
git binary needs to be installed also

### ISSUE THREAD

**Issue by sotcsa** [1inch/shieldy#141]
## Issue
Git is not installed but yarn install tries to use it.

## How to reproduce:
Fresh git clone
docker-compse up

The log shows the error
```
Step 5/14 : COPY ./package.json .
 ---> 58f5e723404f
Step 6/14 : COPY ./yarn.lock .
 ---> ff8e79f2ced8
Step 7/14 : RUN yarn install
 ---> Running in 8b8661f0c537
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find the binary git
```

## Suggested fix: 
add git to list of installable packages:
https://github.com/1inch/shieldy/blob/afb7e312cb95600ceb17cd2a8704eed1871f6f5b/Dockerfile#L15

**Comment by backmeupplz** [comment]
@PeterDaveHello is there any chance you can help with this?

**Comment by PeterDaveHello** [comment]
Well ... it's caused by 9378f0b26e9302e43fee3cb4c67acc9caac3d6b2 and the following 6b70ed74b5c4e0e0bfa5b98345f0f62f588fb5b5, 75d6523afb48d0c587cc462539cf8ad094f3b8c0, I'd send a pull request to add git into Docker image.

**Comment by PeterDaveHello** [comment]
#142 should fix it

**Comment by backmeupplz** [comment]
@PeterDaveHello thank you a lot for the fixes! :)

**Comment by sotcsa** [comment]
Many thanks, a really quick fix, awesome!
